// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.Test;

import java.util.HashMap;
import java.util.Map;



public class TestSelenium {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void testssologin() {
        String url = "";
        String user = "jung915";
        String pass = "IamJung915";
        String captcha = "";
        // Test name: test-sso-login
        // Step # | name | target | value
        // 1 | open | /home?4 |
        driver.get("url");
        // 2 | setWindowSize | 1854x1053 |
        driver.manage().window().setSize(new Dimension(1854, 1053));
        // 3 | click | css=.sfHover div |
        driver.findElement(By.cssSelector(".sfHover div")).click();
        // 4 | click | id=id57 |
        //driver.findElement(By.id("id57")).click();

        // 5 | type | id=id57 | jung915
        //driver.findElement(By.id("id57")).sendKeys("jung915");
        driver.findElement(By.xpath("/html/body/div[1]/div/div/div/div[2]/form/div[2]/input"))
                .sendKeys(user);
        // 6 | type | id=id56 | IamJung915
        driver.findElement(By.xpath("")).sendKeys(pass);
        // 7 | type | name=captchatext | 414
        driver.findElement(By.xpath("captchatext")).sendKeys(captcha);
        // 8 | click | id=id4a |
        driver.findElement(By.xpath("/html/body/div[1]/div/div/div/div[2]/div[3]/button"))
                .click();
    }

}
